apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: onlt0e4eb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: onlt0e4eb-python 
  name: onlt0e4eb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: onlt0e4eb-python 
